language: java
jdk:
  - oraclejdk7
notifications:
  email:
    recipients:
      - ldp4j-commits@googlegroups.com
    on_success: always
    on_failure: always
before_install :
 - git fetch --unshallow # we need a full clone for the build
script: "mvn deploy -Dossrh --settings config/target/classes/ci/settings.xml"
env:
  global:
   - secure: "huXk6otUYsg6kfy+pLJDQSGJLThOuoh6cfmu0USsf2Hc4xlSa7tXYroagO+GL43EkmtpziMf8S7bnaQNPvuj2pA/4ZFAgks6o8GMrvefR6ssWyDKtFdP3k/0d/gvYPj0+CnNELXq1+govjjwWlqy0c57HszgvrbI+4ZcExyW6vY="
   - secure: "jkRsbfTTfgV/HhyCN0GNJF9Y80jmAg8W3sHZkPA/8Kb1p0B9Q4KGDEhtfE5mUZ0dhgT2IYdzmhC2MwxTEx76WjJmRNQX6XXnInQvuZaR2uD7RGIVbDUdcnw4XV4wF6BLg5fb5TBNCXTfdv3GVmK5rBQ+YlBYtK2fW2O3RRXiH+k="
