language: java
jdk:
- oraclejdk7
notifications:
  email:
    recipients:
    - ldp4j-commits@googlegroups.com
    on_success: always
    on_failure: always
before_install:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in config/src/main/resources/ci/secring.gpg.enc -out local.secring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in config/src/main/resources/ci/pubring.gpg.enc -out local.pubring.gpg -d
- git fetch --unshallow
- git checkout ${TRAVIS_BRANCH}
script: if [ ${TRAVIS_PULL_REQUEST} = 'false' ]; then mvn deploy -Dossrh -Dcodebase.directory=`pwd` --settings config/src/main/resources/ci/settings.xml; else mvn clean verify -Dcodebase.directory=`pwd` --settings config/src/main/resources/ci/settings.xml; fi
env:
  global:
  - secure: huXk6otUYsg6kfy+pLJDQSGJLThOuoh6cfmu0USsf2Hc4xlSa7tXYroagO+GL43EkmtpziMf8S7bnaQNPvuj2pA/4ZFAgks6o8GMrvefR6ssWyDKtFdP3k/0d/gvYPj0+CnNELXq1+govjjwWlqy0c57HszgvrbI+4ZcExyW6vY=
  - secure: jkRsbfTTfgV/HhyCN0GNJF9Y80jmAg8W3sHZkPA/8Kb1p0B9Q4KGDEhtfE5mUZ0dhgT2IYdzmhC2MwxTEx76WjJmRNQX6XXnInQvuZaR2uD7RGIVbDUdcnw4XV4wF6BLg5fb5TBNCXTfdv3GVmK5rBQ+YlBYtK2fW2O3RRXiH+k=
  - secure: H2seGILYHufH/fV52QQWr3iZZsj72lF63SzcAy9RYjmwcjNx0ArbU5KuM9oUGgKFylNdDDfFOE9+pIAZXQh9Xmo7sPnod9vbPHYWh+7F1oa8GruCVcA+kEJRNEhlD5l/2/6x797GRkrm8/Ta4flEw38xaeLL2ThisKkP5mbyius=
